SELECT 'USERS' as table_name, COUNT(*) as count FROM users
UNION ALL
SELECT 'CLIENTS', COUNT(*) FROM clients
UNION ALL
SELECT 'SERVICES', COUNT(*) FROM services
UNION ALL
SELECT 'SERVICE_CATEGORIES', COUNT(*) FROM service_categories
UNION ALL
SELECT 'APPOINTMENTS', COUNT(*) FROM appointments;
